#! /bin/bash

. .env

case "$1" in

	build)
		go build -o elwinar ./app
		gulp
	;;

	start)
		./elwinar --port=$PORT --database=$DATABASE --secret=$SECRET --password=$PASSWORD --views=$VIEWS --base=$BASE > elwinar.log 2>&1 &
	;;

	stop)
		kill -SIGINT `pidof elwinar`
	;;

esac
exit 0
