#! /bin/bash

. .env

case "$1" in

	build)
		go build -o elwinar .
	;;

	build-assets)
		gulp
	;;

	start)
		./elwinar > elwinar.log 2>&1 &
	;;

	stop)
		kill -SIGINT `pidof elwinar`
	;;

esac
exit 0
